/**
 * Project AntAi
 * @author Phillip
 * @version 1.0.0
 */


#ifndef _ACTION_H
#define _ACTION_H

enum Action {
	NONE,
	MOVE_LEFT, MOVE_UP, MOVE_RIGHT, MOVE_DOWN,
	DIG_LEFT, DIG_UP, DIG_RIGHT, DIG_DOWN,
	ATTACK_LEFT, ATTACK_UP, ATTACK_RIGHT, ATTACK_DOWN,
	PICKUP_LEFT, PICKUP_UP, PICKUP_RIGHT, PICKUP_DOWN,
	PUTDOWN_LEFT, PUTDOWN_UP, PUTDOWN_RIGHT, PUTDOWN_DOWN,
	EAT,
	SHARE_KNOWLEDGE
};

#endif //_ACTION_H