/**
 * Project AntAi
 * @author Phillip
 * @version 1.0.0
 */


#ifndef _AGENT_H
#define _AGENT_H

#include "cocos2d.h"
#include "Action.h"
#include "CreatureMap.h"
#include <string>

class Agent {
public: 
    /**
	* The visibleMap is a representation of what the creature can see from where it stands.
	* The creatureMap is the map generated by the creature as it moves around and gets knowledge from other creatures.
	* The currentItem is the type of item, the creature is carrying or an empty string if nothing is carried.
	*/
    virtual Action step(int hp, cocos2d::Point pos, CreatureMap creatureGameMap, std::string currentItem, Action lastAction);
};

#endif //_AGENT_H