/**
* Project AntAi
* @author Phillip
* @version 1.0.0
*/


#ifndef _ANT_AGENT_H
#define _ANT_AGENT_H

#include "Agent.h"

class AntAgent : public Agent {
public:
	/**
	* The visibleMap is a representation of what the creature can see from where it stands.
	* The creatureMap is the map generated by the creature as it moves around and gets knowledge from other creatures.
	* The currentItem is the type of item, the creature is carrying or an empty string if nothing is carried.
	*/
	AgentAction step(int hp, cocos2d::Point pos, CreatureMap creatureGameMap, std::string currentItem, AgentAction lastAction);
};

#endif //ANT_